/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWatchesRouteImport } from './routes/api/watches'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiWatchesIdRouteImport } from './routes/api/watches.$id'
import { Route as ApiSchedulerTickRouteImport } from './routes/api/scheduler/tick'
import { Route as ApiResearchStatusRouteImport } from './routes/api/research/status'
import { Route as ApiResearchOpportunitiesRouteImport } from './routes/api/research/opportunities'
import { Route as ApiDaytonaStatusRouteImport } from './routes/api/daytona/status'
import { Route as ApiDaytonaRunOpportunityRouteImport } from './routes/api/daytona/run-opportunity'
import { Route as ApiWatchesIdRunRouteImport } from './routes/api/watches.$id.run'
import { Route as ApiPublicKeypSearchRouteImport } from './routes/api/public/keyp/search'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchesRoute = ApiWatchesRouteImport.update({
  id: '/api/watches',
  path: '/api/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchesIdRoute = ApiWatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWatchesRoute,
} as any)
const ApiSchedulerTickRoute = ApiSchedulerTickRouteImport.update({
  id: '/api/scheduler/tick',
  path: '/api/scheduler/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchStatusRoute = ApiResearchStatusRouteImport.update({
  id: '/api/research/status',
  path: '/api/research/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchOpportunitiesRoute =
  ApiResearchOpportunitiesRouteImport.update({
    id: '/api/research/opportunities',
    path: '/api/research/opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDaytonaStatusRoute = ApiDaytonaStatusRouteImport.update({
  id: '/api/daytona/status',
  path: '/api/daytona/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDaytonaRunOpportunityRoute =
  ApiDaytonaRunOpportunityRouteImport.update({
    id: '/api/daytona/run-opportunity',
    path: '/api/daytona/run-opportunity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWatchesIdRunRoute = ApiWatchesIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ApiWatchesIdRoute,
} as any)
const ApiPublicKeypSearchRoute = ApiPublicKeypSearchRouteImport.update({
  id: '/api/public/keyp/search',
  path: '/api/public/keyp/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/watches': typeof ApiWatchesRouteWithChildren
  '/api/daytona/run-opportunity': typeof ApiDaytonaRunOpportunityRoute
  '/api/daytona/status': typeof ApiDaytonaStatusRoute
  '/api/research/opportunities': typeof ApiResearchOpportunitiesRoute
  '/api/research/status': typeof ApiResearchStatusRoute
  '/api/scheduler/tick': typeof ApiSchedulerTickRoute
  '/api/watches/$id': typeof ApiWatchesIdRouteWithChildren
  '/api/public/keyp/search': typeof ApiPublicKeypSearchRoute
  '/api/watches/$id/run': typeof ApiWatchesIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/watches': typeof ApiWatchesRouteWithChildren
  '/api/daytona/run-opportunity': typeof ApiDaytonaRunOpportunityRoute
  '/api/daytona/status': typeof ApiDaytonaStatusRoute
  '/api/research/opportunities': typeof ApiResearchOpportunitiesRoute
  '/api/research/status': typeof ApiResearchStatusRoute
  '/api/scheduler/tick': typeof ApiSchedulerTickRoute
  '/api/watches/$id': typeof ApiWatchesIdRouteWithChildren
  '/api/public/keyp/search': typeof ApiPublicKeypSearchRoute
  '/api/watches/$id/run': typeof ApiWatchesIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/watches': typeof ApiWatchesRouteWithChildren
  '/api/daytona/run-opportunity': typeof ApiDaytonaRunOpportunityRoute
  '/api/daytona/status': typeof ApiDaytonaStatusRoute
  '/api/research/opportunities': typeof ApiResearchOpportunitiesRoute
  '/api/research/status': typeof ApiResearchStatusRoute
  '/api/scheduler/tick': typeof ApiSchedulerTickRoute
  '/api/watches/$id': typeof ApiWatchesIdRouteWithChildren
  '/api/public/keyp/search': typeof ApiPublicKeypSearchRoute
  '/api/watches/$id/run': typeof ApiWatchesIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/opportunities'
    | '/sitemap.xml'
    | '/api/notifications'
    | '/api/watches'
    | '/api/daytona/run-opportunity'
    | '/api/daytona/status'
    | '/api/research/opportunities'
    | '/api/research/status'
    | '/api/scheduler/tick'
    | '/api/watches/$id'
    | '/api/public/keyp/search'
    | '/api/watches/$id/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/opportunities'
    | '/sitemap.xml'
    | '/api/notifications'
    | '/api/watches'
    | '/api/daytona/run-opportunity'
    | '/api/daytona/status'
    | '/api/research/opportunities'
    | '/api/research/status'
    | '/api/scheduler/tick'
    | '/api/watches/$id'
    | '/api/public/keyp/search'
    | '/api/watches/$id/run'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/opportunities'
    | '/sitemap.xml'
    | '/api/notifications'
    | '/api/watches'
    | '/api/daytona/run-opportunity'
    | '/api/daytona/status'
    | '/api/research/opportunities'
    | '/api/research/status'
    | '/api/scheduler/tick'
    | '/api/watches/$id'
    | '/api/public/keyp/search'
    | '/api/watches/$id/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiWatchesRoute: typeof ApiWatchesRouteWithChildren
  ApiDaytonaRunOpportunityRoute: typeof ApiDaytonaRunOpportunityRoute
  ApiDaytonaStatusRoute: typeof ApiDaytonaStatusRoute
  ApiResearchOpportunitiesRoute: typeof ApiResearchOpportunitiesRoute
  ApiResearchStatusRoute: typeof ApiResearchStatusRoute
  ApiSchedulerTickRoute: typeof ApiSchedulerTickRoute
  ApiPublicKeypSearchRoute: typeof ApiPublicKeypSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watches': {
      id: '/api/watches'
      path: '/api/watches'
      fullPath: '/api/watches'
      preLoaderRoute: typeof ApiWatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watches/$id': {
      id: '/api/watches/$id'
      path: '/$id'
      fullPath: '/api/watches/$id'
      preLoaderRoute: typeof ApiWatchesIdRouteImport
      parentRoute: typeof ApiWatchesRoute
    }
    '/api/scheduler/tick': {
      id: '/api/scheduler/tick'
      path: '/api/scheduler/tick'
      fullPath: '/api/scheduler/tick'
      preLoaderRoute: typeof ApiSchedulerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/status': {
      id: '/api/research/status'
      path: '/api/research/status'
      fullPath: '/api/research/status'
      preLoaderRoute: typeof ApiResearchStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/opportunities': {
      id: '/api/research/opportunities'
      path: '/api/research/opportunities'
      fullPath: '/api/research/opportunities'
      preLoaderRoute: typeof ApiResearchOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daytona/status': {
      id: '/api/daytona/status'
      path: '/api/daytona/status'
      fullPath: '/api/daytona/status'
      preLoaderRoute: typeof ApiDaytonaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daytona/run-opportunity': {
      id: '/api/daytona/run-opportunity'
      path: '/api/daytona/run-opportunity'
      fullPath: '/api/daytona/run-opportunity'
      preLoaderRoute: typeof ApiDaytonaRunOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watches/$id/run': {
      id: '/api/watches/$id/run'
      path: '/run'
      fullPath: '/api/watches/$id/run'
      preLoaderRoute: typeof ApiWatchesIdRunRouteImport
      parentRoute: typeof ApiWatchesIdRoute
    }
    '/api/public/keyp/search': {
      id: '/api/public/keyp/search'
      path: '/api/public/keyp/search'
      fullPath: '/api/public/keyp/search'
      preLoaderRoute: typeof ApiPublicKeypSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiWatchesIdRouteChildren {
  ApiWatchesIdRunRoute: typeof ApiWatchesIdRunRoute
}

const ApiWatchesIdRouteChildren: ApiWatchesIdRouteChildren = {
  ApiWatchesIdRunRoute: ApiWatchesIdRunRoute,
}

const ApiWatchesIdRouteWithChildren = ApiWatchesIdRoute._addFileChildren(
  ApiWatchesIdRouteChildren,
)

interface ApiWatchesRouteChildren {
  ApiWatchesIdRoute: typeof ApiWatchesIdRouteWithChildren
}

const ApiWatchesRouteChildren: ApiWatchesRouteChildren = {
  ApiWatchesIdRoute: ApiWatchesIdRouteWithChildren,
}

const ApiWatchesRouteWithChildren = ApiWatchesRoute._addFileChildren(
  ApiWatchesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiWatchesRoute: ApiWatchesRouteWithChildren,
  ApiDaytonaRunOpportunityRoute: ApiDaytonaRunOpportunityRoute,
  ApiDaytonaStatusRoute: ApiDaytonaStatusRoute,
  ApiResearchOpportunitiesRoute: ApiResearchOpportunitiesRoute,
  ApiResearchStatusRoute: ApiResearchStatusRoute,
  ApiSchedulerTickRoute: ApiSchedulerTickRoute,
  ApiPublicKeypSearchRoute: ApiPublicKeypSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
